function games() {
  return [
    {
      img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg?t=1671485009",
      name: "Red Dead Redemption 2",
      category: "Shooter",
      link: "https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/",
    },
    {
      img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1238840/header.jpg?t=1664070400",
      name: "Battlefield 1",
      category: "Shooter",
      link: "https://store.steampowered.com/app/1238840/Battlefield_1/",
    },
    {
      img: "https://cdn.cloudflare.steamstatic.com/steam/apps/311210/header.jpg?t=1646763462",
      name: "Call of Duty: Black Ops 3",
      category: "Shooter",
      link: "https://store.steampowered.com/app/311210/Call_of_Duty_Black_Ops_III/",
    },
    {
      img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1237950/header.jpg?t=1651767512",
      name: "Battlefront 2",
      category: "Shooter",
      link: "https://store.steampowered.com/app/1237950/STAR_WARS_Battlefront_II/",
    },
    {
      img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1659040/header.jpg?t=1674843959",
      name: "Hitman 3",
      category: "Shooter",
      link: "https://store.steampowered.com/app/1659040/HITMAN_3/",
    },
    {
      img: "https://cdn.cloudflare.steamstatic.com/steam/apps/10180/header.jpg?t=1654809646",
      name: "Call of Duty: Modern Warfare 2",
      category: "Shooter",
      link: "https://store.steampowered.com/app/1938090/Call_of_Duty_Modern_Warfare_II/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/2221490/header.jpg?t=1674233942",
      name: "Division 2",
      category: "Shooter",
      link: "https://store.steampowered.com/app/2221490/Tom_Clancys_The_Division_2/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/2231380/header.jpg?t=1674496956",
      name: "Ghost Recon Breakpoint",
      category: "Shooter",
      link: "https://store.steampowered.com/app/2231380/Tom_Clancys_Ghost_Recon_Breakpoint/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/230410/header.jpg?t=1671045081",
      name: "Warframe",
      category: "Shooter",
      link: "https://store.steampowered.com/app/230410/Warframe/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/440/header.jpg?t=1665425286",
      name: "Team Fortress 2",
      category: "Shooter",
      link: "https://store.steampowered.com/app/440/Team_Fortress_2/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/990080/header.jpg?t=1676056674",
      name: "Hogwarts Legacy",
      category: "Action-Adventure",
      link: "https://store.steampowered.com/app/990080/Hogwarts_Legacy/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/1599340/header.jpg?t=1675876782",
      name: "Lost Ark",
      category: "Action-Adventure",
      link: "https://store.steampowered.com/app/1599340/Lost_Ark/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/1593500/header.jpg?t=1650554420",
      name: "God of War",
      category: "Action-Adventure",
      link: "https://store.steampowered.com/app/1593500/God_of_War/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/1817190/header.jpg?t=1672784176",
      name: "Spider-Man: Miles Morales",
      category: "Action-Adventure",
      link: "https://store.steampowered.com/app/1817190/Marvels_SpiderMan_Miles_Morales/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/489830/header.jpg?t=1650909796",
      name: "Elder Scrolls V: Skyrim",
      category: "Action-Adventure",
      link: "https://store.steampowered.com/app/489830/The_Elder_Scrolls_V_Skyrim_Special_Edition/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/346110/header.jpg?t=1669254188",
      name: "Ark Survival Evolved",
      category: "Action-Adventure",
      link: "https://store.steampowered.com/app/346110/ARK_Survival_Evolved/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/582660/header_alt_assets_21.jpg?t=1674089807",
      name: "Black Desert",
      category: "Action-Adventure",
      link: "https://store.steampowered.com/app/582660/Black_Desert/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/1286830/header.jpg?t=1645090351",
      name: "Star Wars: The Old Republic",
      category: "Action-Adventure",
      link: "https://store.steampowered.com/app/1286830/STAR_WARS_The_Old_Republic/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/1063730/header.jpg?t=1671141281",
      name: "New World",
      category: "Action-Adventure",
      link: "https://store.steampowered.com/app/1063730/New_World/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/377160/header.jpg?t=1650909928",
      name: "Fallout 4",
      category: "Action-Adventure",
      link: "https://store.steampowered.com/app/377160/Fallout_4/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/1551360/header.jpg?t=1673029404",
      name: "Forza Horizon 5",
      category: "Racing",
      link: "https://store.steampowered.com/app/1551360/Forza_Horizon_5/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/1080110/header.jpg?t=1663755538",
      name: "F1",
      category: "Racing",
      link: "https://store.steampowered.com/app/1692250/F1_22/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/646910/header.jpg?t=1675702496",
      name: "The Crew 2",
      category: "Racing",
      link: "https://store.steampowered.com/app/646910/The_Crew_2/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/690790/header.jpg?t=1626343640",
      name: "Dirt Rally 2.0",
      category: "Racing",
      link: "https://store.steampowered.com/app/690790/DiRT_Rally_20/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/1222680/header.jpg?t=1667318479",
      name: "Need for Speed Heat",
      category: "Racing",
      link: "https://store.steampowered.com/app/1222680/Need_for_Speed_Heat/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/2990/header.jpg?t=1570210036",
      name: "Flatout 2",
      category: "Racing",
      link: "https://store.steampowered.com/app/2990/FlatOut_2/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/34190/header.jpg?t=1603130276",
      name: "Sonic & Sega All-Stars Racing",
      category: "Racing",
      link: "https://store.steampowered.com/app/34190/Sonic__SEGA_AllStars_Racing/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/11020/header.jpg?t=1548090419",
      name: "Trackmania Nations Forever",
      category: "Racing",
      link: "https://store.steampowered.com/app/2225070/Trackmania/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/1259980/header.jpg?t=1675073172",
      name: "Ride 4",
      category: "Racing",
      link: "https://store.steampowered.com/app/1259980/RIDE_4/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/228380/header.jpg?t=1664963447",
      name: "Wreckfest",
      category: "Racing",
      link: "https://store.steampowered.com/app/228380/Wreckfest/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/252490/header.jpg?t=1671160999",
      name: "Rust",
      category: "MMO",
      link: "https://store.steampowered.com/app/252490/Rust/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/306130/header.jpg?t=1674679947",
      name: "The Elder Scrolls Online",
      category: "MMO",
      link: "https://store.steampowered.com/app/306130/The_Elder_Scrolls_Online/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/39210/header.jpg?t=1669805579",
      name: "Final Fantasy XIV Online",
      category: "MMO",
      link: "https://store.steampowered.com/app/39210/FINAL_FANTASY_XIV_Online/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/221100/header.jpg?t=1674143992",
      name: "DayZ",
      category: "MMO",
      link: "https://store.steampowered.com/app/221100/DayZ/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/238960/header.jpg?t=1675895226",
      name: "Path of Exile",
      category: "MMO",
      link: "https://store.steampowered.com/app/238960/Path_of_Exile/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/1343400/header.jpg?t=1668764247",
      name: "Runescape",
      category: "MMO",
      link: "https://store.steampowered.com/app/1343400/RuneScape/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/1284210/header.jpg?t=1671734300",
      name: "Guild Wars 2",
      category: "MMO",
      link: "https://store.steampowered.com/app/1284210/Guild_Wars_2/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/444200/header.jpg?t=1674827019",
      name: "World of Tank Blitz",
      category: "MMO",
      link: "https://store.steampowered.com/app/444200/World_of_Tanks_Blitz/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/438100/header.jpg?t=1662741577",
      name: "VRChat",
      category: "MMO",
      link: "https://store.steampowered.com/app/438100/VRChat/",
    },
    {
      img: "https://cdn.akamai.steamstatic.com/steam/apps/8500/header.jpg?t=1673003177",
      name: "EVE Online",
      category: "MMO",
      link: "https://store.steampowered.com/app/8500/EVE_Online/",
    },
  ];
}

export default games;
